version: '3'

services:
  postgres:
    image: postgres:14
    container_name: nestkit_postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nestkit

  redis:
    image: redis:7
    container_name: nestkit_redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
    networks:
      - nestkit

volumes:
  postgres-data:
  redis-data:

networks:
  nestkit:
    driver: bridge
